import os

Import('env')

texlib_sources = Split("""
	dtexoutput.cpp
	dtexinput.cpp
	deeptexturetile.cpp
	deeptileadaptor.cpp
	deeptilearray.cpp
	deeptexture.cpp
	deepfileheader.cpp
	""")

texlib_headers = Split("""
	dtexoutput.h
	dtexinput.h
	deeptexturetile.h
	deeptileadaptor.h
	deeptilearray.h
	deeptexture.h
	deepfileheader.h
	""")

texlibenv = env.Copy()
texlibenv.AppendUnique(CPPPATH=['$tiff_include_path'])

texlibenv.AppendUnique(LIBS = ['aqsistypes', '$tiff_lib'])
texlibenv.AppendUnique(CPPPATH=['$tiff_include_path'])

# I don't want the line below, since I am not using tiffile.cpp/h?
#texlibenv.Replace(LIBS = ['aqsistypes', '$tiff_lib', '$tiffxx_lib'])
texlibenv.UseTargetOptions('texlib')

texlib = texlibenv.SharedLibrary('aqsistex', [texlib_sources]);
texlibenv.PostBuildSharedLibrary(texlibenv, texlib)

texlibenv.InstallAs([os.path.join('${RENDERENGINEDIR}', '%s${SHLIB_VERSION_SUFFIX}') % (texlib[0],)], [texlib[0]])
texlibenv.PostInstallSharedLibrary(texlibenv, '${RENDERENGINEDIR}', texlib)

#-------------------------------------------------------------------------------
# Unit Tests

texlib_test_sources = Split('''
	''')

Import('testEnv')
testEnv = testEnv.Copy()
testEnv.AppendUnique(LIBS=['aqsistex', 'aqsistypes'])
testEnv.addUnitTest('texlib_test', texlib_test_sources)


env.Distribute(texlib_sources)
env.Distribute(texlib_test_sources)
env.Distribute(texlib_headers)
env.Distribute('SConscript')
